# Generated by Django 5.1.2 on 2024-11-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
